apiVersion: v1
kind: Namespace
metadata:
  name: fake71-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake71-deployment
  namespace: fake71-ns
  labels:
    app: fake71
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake71
  template:
    metadata:
      labels:
        app: fake71
    spec:
      containers:
      - name: fake71
        imagePullPolicy: Always
        image: bunengxiu/fake71:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20071
        livenessProbe:
          tcpSocket:
            port: 20071
          initialDelaySeconds: 710
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20071
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake71-service
  namespace: fake71-ns
  labels:
    app: fake71
spec:
  ports:
    - port: 20071
      protocol: TCP
      targetPort: 20071
  selector:
    app: fake71
  type: NodePort
