apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-ns
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
  type: NodePort