apiVersion: v1
kind: Namespace
metadata:
  name: fake83-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake83-deployment
  namespace: fake83-ns
  labels:
    app: fake83
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake83
  template:
    metadata:
      labels:
        app: fake83
    spec:
      containers:
      - name: fake83
        imagePullPolicy: Always
        image: bunengxiu/fake83:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20083
        livenessProbe:
          tcpSocket:
            port: 20083
          initialDelaySeconds: 830
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20083
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake83-service
  namespace: fake83-ns
  labels:
    app: fake83
spec:
  ports:
    - port: 20083
      protocol: TCP
      targetPort: 20083
  selector:
    app: fake83
  type: NodePort
