apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2
spec:
  type: middleware.http.oauth2
  version: v1
  metadata:
    - name: clientId
      value: "Ov23liLHYxIevfhvPVQy"
    - name: clientSecret
      value: "9f1cd330b490f876ec906c590fc60cf5db0422fc"
    - name: scopes
      value: ""
    - name: authURL
      value: "https://github.com/login/oauth/authorize"
    - name: tokenURL
      value: "https://github.com/login/oauth/access_token"
    - name: redirectURL
      value: "http://echo.dev.dolphin.top"
    - name: authHeaderName
      value: "authorization"