apiVersion: v1
kind: Namespace
metadata:
  name: fake20-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake20-deployment
  namespace: fake20-ns
  labels:
    app: fake20
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake20
  template:
    metadata:
      labels:
        app: fake20
    spec:
      containers:
      - name: fake20
        imagePullPolicy: Always
        image: bunengxiu/fake20:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20020
        livenessProbe:
          tcpSocket:
            port: 20020
          initialDelaySeconds: 300
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20020
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake20-service
  namespace: fake20-ns
  labels:
    app: fake20
spec:
  ports:
    - port: 20020
      protocol: TCP
      targetPort: 20020
  selector:
    app: fake20
  type: NodePort
