apiVersion: v1
kind: Namespace
metadata:
  name: fake8-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake8-deployment
  namespace: fake8-ns
  labels:
    app: fake8
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake8
  template:
    metadata:
      labels:
        app: fake8
    spec:
      containers:
      - name: fake8
        imagePullPolicy: Always
        image: bunengxiu/fake8:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20008
        livenessProbe:
          tcpSocket:
            port: 20008
          initialDelaySeconds: 300
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20008
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake8-service
  namespace: fake8-ns
  labels:
    app: fake8
spec:
  ports:
    - port: 20008
      protocol: TCP
      targetPort: 20008
  selector:
    app: fake8
  type: NodePort
