apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-pvc
  namespace: tekton-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: ci-pv
