apiVersion: v1
kind: Namespace
metadata:
  name: fake67-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake67-deployment
  namespace: fake67-ns
  labels:
    app: fake67
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake67
  template:
    metadata:
      labels:
        app: fake67
    spec:
      containers:
      - name: fake67
        imagePullPolicy: Always
        image: bunengxiu/fake67:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20067
        livenessProbe:
          tcpSocket:
            port: 20067
          initialDelaySeconds: 670
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20067
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake67-service
  namespace: fake67-ns
  labels:
    app: fake67
spec:
  ports:
    - port: 20067
      protocol: TCP
      targetPort: 20067
  selector:
    app: fake67
  type: NodePort
