apiVersion: v1
kind: Service
metadata:
  name: penguin-service
  namespace: penguin-ns
  labels:
    app: penguin
spec:
  ports:
    - port: 10000
      protocol: TCP
      targetPort: 10000
  selector:
    app: penguin
  type: NodePort
