apiVersion: apps/v1
kind: Deployment
metadata:
  name: penguin-deployment
  namespace: penguin-ns
  labels:
    app: penguin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: penguin
  template:
    metadata:
      labels:
        app: penguin
    spec:
      containers:
      - name: penguin
        imagePullPolicy: Always
        image: bunengxiu/penguin:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 10000
        livenessProbe:
          tcpSocket:
            port: 10000
          initialDelaySeconds: 300
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 10000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
