apiVersion: v1
kind: Namespace
metadata:
  name: fake79-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake79-deployment
  namespace: fake79-ns
  labels:
    app: fake79
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake79
  template:
    metadata:
      labels:
        app: fake79
    spec:
      containers:
      - name: fake79
        imagePullPolicy: Always
        image: bunengxiu/fake79:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20079
        livenessProbe:
          tcpSocket:
            port: 20079
          initialDelaySeconds: 790
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20079
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake79-service
  namespace: fake79-ns
  labels:
    app: fake79
spec:
  ports:
    - port: 20079
      protocol: TCP
      targetPort: 20079
  selector:
    app: fake79
  type: NodePort
