apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: traces
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"
#    otel:
#      endpointAddress: "http://openobserve.openobserve.svc.cluster.local:5080/api/default/"