apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "web"
        dapr.io/app-port: "40000"
        dapr.io/enable-api-logging: "true"
        instrumentation.opentelemetry.io/inject-python: "opentelemetry-collector/python-instrumentation"
        sidecar.opentelemetry.io/inject: "opentelemetry-collector/sidecar"
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: web
        imagePullPolicy: Always
        image: bunengxiu/dapr-microservice-web:latest
        ports:
          - containerPort: 40000