apiVersion: v1
kind: PersistentVolume
metadata:
  name: cd-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tekton/source/cd
