apiVersion: v1
kind: Namespace
metadata:
  name: fake72-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake72-deployment
  namespace: fake72-ns
  labels:
    app: fake72
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake72
  template:
    metadata:
      labels:
        app: fake72
    spec:
      containers:
      - name: fake72
        imagePullPolicy: Always
        image: bunengxiu/fake72:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20072
        livenessProbe:
          tcpSocket:
            port: 20072
          initialDelaySeconds: 720
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20072
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake72-service
  namespace: fake72-ns
  labels:
    app: fake72
spec:
  ports:
    - port: 20072
      protocol: TCP
      targetPort: 20072
  selector:
    app: fake72
  type: NodePort
