apiVersion: v1
kind: Service
metadata:
  name: whale-service
  namespace: whale-ns
  labels:
    app: whale
spec:
  ports:
    - port: 10001
      protocol: TCP
      targetPort: 10001
  selector:
    app: whale
  type: NodePort
