apiVersion: apps/v1
kind: Deployment
metadata:
  name: whale-deployment
  namespace: whale-ns
  labels:
    app: whale
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whale
  template:
    metadata:
      labels:
        app: whale
    spec:
      containers:
      - name: whale
        imagePullPolicy: Always
        image: bunengxiu/whale:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 10001
        livenessProbe:
          tcpSocket:
            port: 10001
          initialDelaySeconds: 300
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 10001
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
