apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: efak-ns
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
