apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: efak-ns
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          imagePullPolicy: IfNotPresent
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
          env:
            - name: POSTGRES_DB
              value: "efak"
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
