apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka-ns
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: kafka-port-1
    port: 9092
    targetPort: 9092
  - protocol: TCP
    name: kafka-port-2
    port: 9094
    targetPort: 9094
  selector:
    app: kafka
