apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: kafka-ns
  labels:
    app: zookeeper
spec:
  type: NodePort
  ports:
  - name: zookeeper-port
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper