apiVersion: v1
kind: Namespace
metadata:
  name: fake42-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake42-deployment
  namespace: fake42-ns
  labels:
    app: fake42
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake42
  template:
    metadata:
      labels:
        app: fake42
    spec:
      containers:
      - name: fake42
        imagePullPolicy: Always
        image: bunengxiu/fake42:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20042
        livenessProbe:
          tcpSocket:
            port: 20042
          initialDelaySeconds: 420
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20042
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake42-service
  namespace: fake42-ns
  labels:
    app: fake42
spec:
  ports:
    - port: 20042
      protocol: TCP
      targetPort: 20042
  selector:
    app: fake42
  type: NodePort
