apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: traefik-ns
  labels:
    app: traefik-ns
spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik
