apiVersion: v1
kind: Namespace
metadata:
  name: fake26-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake26-deployment
  namespace: fake26-ns
  labels:
    app: fake26
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake26
  template:
    metadata:
      labels:
        app: fake26
    spec:
      containers:
      - name: fake26
        imagePullPolicy: Always
        image: bunengxiu/fake26:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20026
        livenessProbe:
          tcpSocket:
            port: 20026
          initialDelaySeconds: 300
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20026
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake26-service
  namespace: fake26-ns
  labels:
    app: fake26
spec:
  ports:
    - port: 20026
      protocol: TCP
      targetPort: 20026
  selector:
    app: fake26
  type: NodePort
