apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  namespace: opentelemetry-collector
spec:
  config: |
    receivers:
      otlp:
        protocols:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug:
      otlphttp/openobserve:
        endpoint: http://openobserve.openobserve.svc.cluster.local:5080/api/default/
        headers:
          Authorization: Basic YnVuZW5neGl1QDE2My5jb206YWRtaW4xMjM=
          stream-name: default

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlphttp/openobserve]
