apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight-deployment
  namespace: redisinsight-ns
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
      - name: redisinsight
        image: redislabs/redisinsight
        ports:
        - containerPort: 8001
          protocol: TCP
        volumeMounts:
          - mountPath: /db
            name: db
      volumes:
        - name: db
          emptyDir: {}
