apiVersion: v1
kind: Namespace
metadata:
  name: fake62-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake62-deployment
  namespace: fake62-ns
  labels:
    app: fake62
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake62
  template:
    metadata:
      labels:
        app: fake62
    spec:
      containers:
      - name: fake62
        imagePullPolicy: Always
        image: bunengxiu/fake62:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20062
        livenessProbe:
          tcpSocket:
            port: 20062
          initialDelaySeconds: 620
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20062
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake62-service
  namespace: fake62-ns
  labels:
    app: fake62
spec:
  ports:
    - port: 20062
      protocol: TCP
      targetPort: 20062
  selector:
    app: fake62
  type: NodePort
