apiVersion: v1
kind: Namespace
metadata:
  name: fake48-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake48-deployment
  namespace: fake48-ns
  labels:
    app: fake48
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake48
  template:
    metadata:
      labels:
        app: fake48
    spec:
      containers:
      - name: fake48
        imagePullPolicy: Always
        image: bunengxiu/fake48:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20048
        livenessProbe:
          tcpSocket:
            port: 20048
          initialDelaySeconds: 480
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20048
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake48-service
  namespace: fake48-ns
  labels:
    app: fake48
spec:
  ports:
    - port: 20048
      protocol: TCP
      targetPort: 20048
  selector:
    app: fake48
  type: NodePort
