apiVersion: v1
kind: Namespace
metadata:
  name: fake99-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake99-deployment
  namespace: fake99-ns
  labels:
    app: fake99
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake99
  template:
    metadata:
      labels:
        app: fake99
    spec:
      containers:
      - name: fake99
        imagePullPolicy: Always
        image: bunengxiu/fake99:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20099
        livenessProbe:
          tcpSocket:
            port: 20099
          initialDelaySeconds: 990
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20099
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake99-service
  namespace: fake99-ns
  labels:
    app: fake99
spec:
  ports:
    - port: 20099
      protocol: TCP
      targetPort: 20099
  selector:
    app: fake99
  type: NodePort
