apiVersion: v1
kind: Namespace
metadata:
  name: fake63-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake63-deployment
  namespace: fake63-ns
  labels:
    app: fake63
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake63
  template:
    metadata:
      labels:
        app: fake63
    spec:
      containers:
      - name: fake63
        imagePullPolicy: Always
        image: bunengxiu/fake63:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20063
        livenessProbe:
          tcpSocket:
            port: 20063
          initialDelaySeconds: 630
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20063
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake63-service
  namespace: fake63-ns
  labels:
    app: fake63
spec:
  ports:
    - port: 20063
      protocol: TCP
      targetPort: 20063
  selector:
    app: fake63
  type: NodePort
