apiVersion: v1
kind: Namespace
metadata:
  name: fake39-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake39-deployment
  namespace: fake39-ns
  labels:
    app: fake39
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake39
  template:
    metadata:
      labels:
        app: fake39
    spec:
      containers:
      - name: fake39
        imagePullPolicy: Always
        image: bunengxiu/fake39:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20039
        livenessProbe:
          tcpSocket:
            port: 20039
          initialDelaySeconds: 390
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20039
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake39-service
  namespace: fake39-ns
  labels:
    app: fake39
spec:
  ports:
    - port: 20039
      protocol: TCP
      targetPort: 20039
  selector:
    app: fake39
  type: NodePort
