apiVersion: v1
kind: Namespace
metadata:
  name: fake93-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake93-deployment
  namespace: fake93-ns
  labels:
    app: fake93
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake93
  template:
    metadata:
      labels:
        app: fake93
    spec:
      containers:
      - name: fake93
        imagePullPolicy: Always
        image: bunengxiu/fake93:1.0.0
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 20093
        livenessProbe:
          tcpSocket:
            port: 20093
          initialDelaySeconds: 930
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 20093
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fake93-service
  namespace: fake93-ns
  labels:
    app: fake93
spec:
  ports:
    - port: 20093
      protocol: TCP
      targetPort: 20093
  selector:
    app: fake93
  type: NodePort
