apiVersion: v1
kind: Service
metadata:
  name: pgadmin4-service
  namespace: pgadmin4-ns
  labels:
    app: pgadmin4
spec:
  type: NodePort
  ports:
    - name: pgadmin4-port
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: pgadmin4