apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4-deployment
  namespace: pgadmin4-ns
  labels:
    app: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "bunengxiu@163.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin4-secret
                  key: pgadmin-default-password
            - name: PGADMIN_PORT
              value: "80"
          ports:
            - containerPort: 80
              protocol: TCP
