apiVersion: v1
kind: Service
metadata:
  name: shark-service
  namespace: shark-ns
  labels:
    app: shark
spec:
  ports:
    - port: 10002
      protocol: TCP
      targetPort: 10002
  selector:
    app: shark
    version: 1.0.1
  type: NodePort