apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-deployment
  namespace: shark-ns
  labels:
    app: shark
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: shark
  template:
    metadata:
      labels:
        app: shark
    spec:
      containers:
      - name: shark
        imagePullPolicy: Always
        image: bunengxiu/shark:1.0.1
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: 10002
        livenessProbe:
          tcpSocket:
            port: 10002
          initialDelaySeconds: 300
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 10002
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3